title: One-Shot Recognition of Manufacturing Defects in Steel Surfaces
description: <a href="https://doi.org/10.1016/j.promfg.2020.05.146">paper</a>
show_downloads: true
google_analytics: UA-90024709-2
theme: jekyll-theme-cayman
